### ISSUE TITLE
[feature request] add a `_unique` version for all `push()` method

### ISSUE THREAD

**Issue by robinmoussu** [tov/min-max-heap-rs#10]
It would be much more efficient to test for uniqueness when doing the insertion that by iterating over the whole collection. In order to have a min-max-heap of unique elements, I'm currently doing:

```rust
if !my_heap.iter().any(|s| s == &new_item) {
    my_heap.push(new_item)
}
```

The same idea applies to all the methods that insert elements into the heap.

**Comment by tov** [comment]
Hm... There isn't a much more efficient way of doing this than what you're already doing. The way a heap is structured permits repeated elements to be almost arbitrarily far apart, so you don't just find out whether there are duplicates in the natural course of insertion. It requires a worst-case linear-time scan of the heap to search for duplicates.

That said, it may be possible to write a membership checking routine that in the *best case* stops early when the heap invariant guarantees it's seen enough. I don't have time to write that right now, but if you'd like to, I'd consider a PR...

**Comment by robinmoussu** [comment]
> The way a heap is structured permits repeated elements to be almost arbitrarily far apart

That's right, I wrongly though that inserting the same element twice would land at the same place, but I was wrong. If it was true, it wouldn't be a heap, but a binary tree. Thanks!

**Comment by tov** [comment]
Maybe you want treap? Or maybe just an extra hash table on the side?
